language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - peterleepersonal@gmail.com
