#!/usr/bin/env php
<?php
// set to run indefinitely if needed
set_time_limit(0);

set_error_handler(function ($errno, $errstr, $errfile, $errline) {
    // error was suppressed with the @-operator
    if (0 === error_reporting()) {
        return false;
    }

    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use YiiMinifyClientScriptPackage\MinifyCommand;

$application = new Application('YiiMinifyClientScriptPackage', '@package_version@');
$application->add(new MinifyCommand());
$application->run();
